// Game data
const games = [
    {
        id: 1,
        title: "Ark Nova",
        image: "images/ark-nova.jpg",
        rating: 4.8,
        description: "Build the most successful and conservation-focused zoo in this strategic masterpiece.",
        categories: ["Strategy", "Nature", "Animals"],
        complexity: "High",
        playTime: "90-150 min",
        players: "1-4",
        year: 2021,
        designer: "Mathias Wigge",
        publisher: "Feuerland Spiele",
        owned: true,
        wishlist: false,
        featured: true,
        review: "Ark Nova combines the thrill of zoo building with meaningful conservation mechanics. The card-driven gameplay offers multiple paths to victory, whether you focus on creating appealing animal exhibits, participating in conservation projects, or building an efficient economic engine. The game's depth is remarkable, with each decision feeling impactful and the tension building as you race to complete your objectives before other players. The animal cards are beautifully illustrated, and the conservation theme is thoughtfully integrated into the mechanics rather than just being a superficial skin. While the learning curve is steep, the payoff is immensely satisfying. This has quickly become one of my favorite strategic games, offering a perfect blend of theme and mechanics."
    },
    {
        id: 2,
        title: "Forest Shuffle",
        image: "images/forest-shuffle.jpg",
        rating: 4.2,
        description: "A delightful card game featuring woodland creatures and beautiful artwork.",
        categories: ["Card Game", "Nature", "Family"],
        complexity: "Medium",
        playTime: "30-45 min",
        players: "2-5",
        year: 2020,
        designer: "Emma Woods",
        publisher: "Green Leaf Games",
        owned: true,
        wishlist: false,
        featured: true,
        review: "Forest Shuffle brings the woodland to life with its charming illustrations and engaging gameplay. The card drafting and set collection mechanics are familiar enough to be accessible but with enough unique twists to keep experienced gamers interested. I particularly enjoy the seasonal cycle mechanic, where different animals and plants provide varying benefits depending on the current season. The fox cards can be particularly powerful if played at the right moment, creating exciting strategic decisions. While not as deep as some strategy games, Forest Shuffle hits a sweet spot of being easy to teach while offering meaningful choices. It's become a regular feature at family game nights, appealing to both casual players and more serious gamers. The production quality is excellent, with gorgeous artwork that really enhances the woodland theme."
    },
    {
        id: 3,
        title: "Wingspan",
        image: "images/wingspan.jpg",
        rating: 4.7,
        description: "Attract a collection of birds to your wildlife preserve in this award-winning game.",
        categories: ["Strategy", "Nature", "Animals"],
        complexity: "Medium",
        playTime: "40-70 min",
        players: "1-5",
        year: 2019,
        designer: "Elizabeth Hargrave",
        publisher: "Stonemaier Games",
        owned: true,
        wishlist: false,
        featured: false,
        review: "Wingspan soars with its beautiful components and elegant design. The bird cards are not only gorgeous but also educational, featuring real species with accurate habitat information. The engine-building mechanics are satisfying as your aviary grows more efficient with each round. I appreciate how the game rewards different strategies, whether you focus on egg production, card drawing, or food collection. The production quality is exceptional, from the deluxe bird feeder dice tower to the detailed wooden eggs. While some games can feel a bit like multiplayer solitaire, the interaction through shared goals and competition for resources creates just enough player interaction. This has become a staple in my collection and appeals to both serious gamers and those new to the hobby."
    },
    {
        id: 4,
        title: "Everdell",
        image: "images/everdell.jpg",
        rating: 4.5,
        description: "Build a city of critters and constructions in this gorgeous woodland game.",
        categories: ["Strategy", "Nature", "Animals"],
        complexity: "Medium",
        playTime: "40-80 min",
        players: "1-4",
        year: 2018,
        designer: "James A. Wilson",
        publisher: "Starling Games",
        owned: true,
        wishlist: false,
        featured: false,
        review: "Everdell combines worker placement and card tableau building in a charming woodland setting. The game's visual presentation is stunning, from the three-dimensional Ever Tree to the detailed animal meeples. I find the seasonal cycle mechanic particularly engaging, as it creates a natural rhythm to the game and forces interesting decisions about when to recall your workers. The card combinations create satisfying moments when you can chain together multiple actions or trigger special abilities. While the game can feel a bit tight with four players, it scales well and offers a different experience at each player count. The theme is wonderfully integrated into the mechanics, making it easy to immerse yourself in the world of Everdell. This game has earned its place as one of my favorite medium-weight strategy games."
    },
    {
        id: 5,
        title: "Parks",
        image: "images/parks.jpg",
        rating: 4.3,
        description: "Hike through national parks and collect memories in this beautiful game.",
        categories: ["Strategy", "Nature", "Travel"],
        complexity: "Medium",
        playTime: "30-60 min",
        players: "1-5",
        year: 2019,
        designer: "Henry Audubon",
        publisher: "Keymaster Games",
        owned: true,
        wishlist: false,
        featured: false,
        review: "Parks is a visual masterpiece that captures the majesty of America's national parks through stunning illustrations. The gameplay is accessible yet offers meaningful decisions as you move your hikers along the trail, collecting resources and visiting parks. I particularly enjoy the photography mechanic, which adds another layer of strategy as you try to capture specific natural elements. The components are top-notch, from the wooden resource tokens to the thick park cards. While not the deepest game in my collection, Parks offers a perfect balance of strategy and accessibility that makes it ideal for introducing new players to modern board games. The theme resonates strongly, especially for nature lovers, and the gameplay does an excellent job of evoking the feeling of hiking through different seasons."
    },
    {
        id: 6,
        title: "Cascadia",
        image: "images/cascadia.jpg",
        rating: 4.4,
        description: "Build habitats and populate them with wildlife in the Pacific Northwest.",
        categories: ["Strategy", "Nature", "Tile Placement"],
        complexity: "Medium",
        playTime: "30-45 min",
        players: "1-4",
        year: 2021,
        designer: "Randy Flynn",
        publisher: "Flatout Games",
        owned: false,
        wishlist: true,
        featured: false,
        review: ""
    },
    {
        id: 7,
        title: "Meadow",
        image: "images/meadow.jpg",
        rating: 4.1,
        description: "Discover the wonders of nature as you collect cards featuring flora and fauna.",
        categories: ["Card Game", "Nature", "Set Collection"],
        complexity: "Medium",
        playTime: "45-60 min",
        players: "1-4",
        year: 2021,
        designer: "Klemens Kalicki",
        publisher: "Rebel Studio",
        owned: false,
        wishlist: true,
        featured: false,
        review: ""
    }
]; 